apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ping-pong
  name: ping-pong-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
      - image: asia-southeast1-docker.pkg.dev/rational-terra-336303/ping-pong-docker-repo/ping-pong-app:latest
        name: ping-pong-app-image
        resources: {}
        ports:
        - containerPort: 8080
