apiVersion: "v1"
kind: "Service"
metadata:
  name: "ping-pong-service"
  namespace: "default"
  labels:
    app: "ping-pong"
spec:
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  selector:
    app: "ping-pong"
  type: "LoadBalancer"
